### PR TITLE
Swik 1147 provide event transformation and forwarding to lrs

### PR DESCRIPTION
**Pull request by kprist**

### CODE REVIEW

**Comment by kprist** [comment]
This is needed for https://github.com/slidewiki/xAPI-Service/pull/2 to be activated

**Review by dpaun — COMMENTED** [review]
Should there also be a call to a fanout method using pre in the activities.new route (creating multiple activities using the received array)?

**Comment by kprist** [comment]
Yes we should, I missed that, I'll add it as well please mark this as "changes requested". We have another change re: forwarding the user email as well so we'll keep both PRs on hold for a short while.

**Review by dpaun — CHANGES_REQUESTED** [review]
Some changes are needed to handle the 'activities.new' route.

**Review by dpaun — APPROVED** [review]
It looks good!

**Pull request merged**
